services:
  - type: web
    name: kaydatagh
    runtime: static
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /TermsofService
        destination: /Terms.html
      - type: rewrite
        source: /PrivacyPolicy
        destination: /Privacy.html
